name: CME
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '4 0 * * *'
jobs:
  build:
    name: CME tickers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: python3 cme/pairs.py -e nymex | sort > cme/nymex_contracts.txt
      - run: python3 cme/pairs.py -e cme | sort > cme/globex_contract.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cme/
          git diff-index --quiet HEAD || git commit -m "CME: automatic update" -a
          git pull --rebase && git push